[package]
name = "media_archive"
version = "0.1.0"
edition = "2024"

[dependencies]
qbit-rs = "0.4.6"
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["full"] }
toml = "0.9.2"
warp = "0.3.7"
